import type { Metadata } from "next";
import Image from "next/image";
import { ArrowRight, CalendarCheck, MessageCircle, Pencil, Sparkles } from "lucide-react";
import { Reveal } from "@/app/_components/shared/Reveal";
import { getAvailableDesigns } from "@/app/_lib/queries/tattoos";

export const metadata: Metadata = { title: "Diseños disponibles", description: "Explora diseños disponibles para reservar con PajaroMaca." };

export default async function DisenosDisponiblesPage() {
  const availableDesigns = await getAvailableDesigns();
  return (
    <div className="bg-[var(--tattoo-bg)] px-4 py-20 text-[var(--tattoo-text)] sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl">
      <Reveal><section className="max-w-3xl" aria-labelledby="designs-heading"><p className="mb-4 text-xs font-medium uppercase tracking-[.16em] text-[var(--tattoo-accent)]">Piezas para elegir</p><h1 id="designs-heading" className="font-[family-name:var(--font-display)] text-5xl font-bold leading-[.95] tracking-tight sm:text-7xl">Diseños disponibles</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[var(--tattoo-text-muted)]">Explora piezas listas para reservar. Si una ya está reservada, podemos conversar sobre una variación personalizada.</p></section></Reveal>
      <section className="mt-16" aria-label="Catálogo de diseños disponibles"><div className="grid gap-6 md:grid-cols-3">{availableDesigns.map((design, index) => <Reveal key={design.id} delay={index * .08}><article className="group overflow-hidden border border-[var(--tattoo-border)] bg-[var(--tattoo-surface)] transition-colors hover:border-[var(--tattoo-accent)]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={design.src} alt={design.alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-500 group-hover:scale-105" /><span className={`absolute left-4 top-4 inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-medium ${design.status === "Disponible" ? "border-emerald-500/50 bg-emerald-950/80 text-emerald-300" : "border-[var(--tattoo-border)] bg-[#0a0a0a]/85 text-[var(--tattoo-text-muted)]"}`}><span className={`h-1.5 w-1.5 rounded-full ${design.status === "Disponible" ? "bg-emerald-400" : "bg-[var(--tattoo-text-muted)]"}`} aria-hidden="true" />{design.status}</span></div><div className="p-6"><div className="flex items-start justify-between gap-4"><h2 className="font-[family-name:var(--font-display)] text-2xl font-bold">{design.name}</h2><Sparkles className="mt-1 h-5 w-5 shrink-0 text-[var(--tattoo-accent)]" aria-hidden="true" /></div><div className="mt-4 flex flex-wrap gap-2">{[design.style, design.size].filter(Boolean).map((tag) => <span key={tag} className="border border-[var(--tattoo-border)] px-2.5 py-1 text-xs text-[var(--tattoo-text-muted)]">{tag}</span>)}</div><p className="mt-4 text-sm leading-relaxed text-[var(--tattoo-text-muted)]">{design.detail}</p><a className="mt-6 inline-flex items-center gap-2 text-sm font-medium transition-colors hover:text-[var(--tattoo-accent)] focus-visible:outline-2 focus-visible:outline-[var(--tattoo-accent)]" href="/tatuajes/cotizar">Consultar este diseño <ArrowRight className="h-4 w-4" aria-hidden="true" /></a></div></article></Reveal>)}</div></section>
      <section className="mt-24" aria-labelledby="reserve-heading"><Reveal><p className="mb-3 text-xs font-medium uppercase tracking-[.16em] text-[var(--tattoo-accent)]">Del catálogo a tu piel</p><h2 id="reserve-heading" className="font-[family-name:var(--font-display)] text-3xl font-bold sm:text-4xl">Cómo reservar</h2></Reveal><ol className="mt-8 grid gap-4 md:grid-cols-3">{[{ icon: MessageCircle, title: "Elige una pieza", text: "Escríbeme indicando el nombre del diseño que te interesa." }, { icon: Pencil, title: "Ajustamos los detalles", text: "Conversamos sobre ubicación, tamaño y cualquier adaptación." }, { icon: CalendarCheck, title: "Confirmamos tu fecha", text: "Con el diseño listo, coordinamos la sesión y la reserva." }].map(({ icon: Icon, title, text }, index) => <Reveal key={title} delay={index * .08}><li className="border border-[var(--tattoo-border)] bg-[var(--tattoo-surface)] p-6"><div className="flex items-center justify-between"><Icon className="h-6 w-6 text-[var(--tattoo-accent)]" aria-hidden="true" /><span className="text-sm text-[var(--tattoo-text-muted)]">0{index + 1}</span></div><h3 className="mt-8 font-[family-name:var(--font-display)] text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[var(--tattoo-text-muted)]">{text}</p></li></Reveal>)}</ol></section>
      <Reveal delay={.15}><section className="mt-20 flex flex-col gap-6 border border-[var(--tattoo-accent)] bg-[var(--tattoo-accent)] p-6 text-white sm:p-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-white/75">¿Encontraste tu pieza?</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-2xl font-bold sm:text-3xl">Hablemos de cómo llevarla a tu piel.</h2></div><a className="inline-flex items-center justify-center gap-2 border border-white px-5 py-3 font-medium transition-colors hover:bg-white hover:text-[var(--tattoo-accent)]" href="/tatuajes/cotizar">Consultar un diseño <ArrowRight className="h-4 w-4" aria-hidden="true" /></a></section></Reveal>
    </div></div>
  );
}
