import type { Metadata } from "next";
import { MessageCircle } from "lucide-react";
import { Reveal } from "@/app/_components/shared/Reveal";

export const metadata: Metadata = { title: "Cuidados del tatuaje", description: "Guía paso a paso para cuidar tu tatuaje durante la cicatrización." };
const steps = [
  ["Primeras 24 horas", "Deja el vendaje el tiempo indicado en sesión. Luego lávate las manos y limpia suavemente con agua tibia y jabón sin perfume."],
  ["Seca e hidrata", "Seca con toques, usando una toalla limpia. Aplica una capa muy fina de crema recomendada; no lo mantengas empapado."],
  ["Durante la cicatrización", "Lava e hidrata suavemente. Es normal que pique o se descame: no rasques ni arranques las costras."],
  ["Evita por 2 a 4 semanas", "Sol directo, piscinas, jacuzzis, baños largos, fricción y ropa ajustada sobre el tatuaje. Cuando sane, usa bloqueador solar."],
];

export default function CuidadosPage() { const number = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "56912345678"; return <div className="py-24 px-4 sm:px-6 lg:px-8"><div className="max-w-3xl mx-auto"><Reveal><p className="text-[#ef4444] text-xs font-medium tracking-[.16em] uppercase mb-3">Después de la sesión</p><h1 className="font-[family-name:var(--font-space-grotesk)] text-4xl lg:text-6xl font-bold mb-6">Cuida tu tatuaje</h1><p className="text-[#a3a3a3] text-lg">Una guía breve para acompañar una buena cicatrización.</p></Reveal><div className="mt-12 space-y-4">{steps.map(([title, text], i) => <Reveal key={title} delay={i * .08}><section className="bg-[#141414] border border-[#2a2a2a] rounded-xl p-6 sm:p-8"><div className="flex gap-5"><span className="text-[#ef4444] font-[family-name:var(--font-space-grotesk)] text-2xl font-bold">0{i + 1}</span><div><h2 className="font-[family-name:var(--font-space-grotesk)] text-xl font-bold">{title}</h2><p className="text-[#a3a3a3] mt-3 leading-relaxed">{text}</p></div></div></section></Reveal>)}</div><Reveal delay={.4}><div className="mt-10 border border-[#ef4444]/50 bg-[#ef4444]/10 rounded-xl p-6"><h2 className="font-bold">¿Algo no se ve bien?</h2><p className="text-[#a3a3a3] mt-2">Ante fiebre, pus, dolor creciente o enrojecimiento que se expande, consulta a un profesional de salud. También puedes escribirme si tienes dudas sobre la sesión.</p><a className="inline-flex items-center gap-2 text-[#f5f5f5] mt-5 hover:text-[#ef4444]" href={`https://wa.me/${number}?text=${encodeURIComponent("Hola, tengo una pregunta sobre la cicatrización de mi tatuaje.")}`} target="_blank" rel="noopener noreferrer"><MessageCircle className="w-4 h-4" aria-hidden="true" /> Consultar por WhatsApp</a></div></Reveal></div></div>; }
