import type { Metadata } from "next";
import { AlertCircle, CircleCheck, Droplets, Hand, MessageCircle, Moon, Shirt, Sun, Waves } from "lucide-react";
import { Reveal } from "@/app/_components/shared/Reveal";

export const metadata: Metadata = { title: "Cuidados del tatuaje", description: "Guía paso a paso para cuidar tu tatuaje durante la cicatrización." };
const healingStages = [
  { icon: Droplets, title: "Primeras 24 h", text: "Deja el vendaje el tiempo indicado en sesión. Luego lava suavemente con agua tibia y jabón sin perfume; seca con toques." },
  { icon: Hand, title: "Días 2–5", text: "Aplica una capa muy fina de crema recomendada. Puede aparecer sensibilidad, picazón o una leve descamación." },
  { icon: Moon, title: "Semana 2", text: "Continúa lavando e hidratando sin rascar ni arrancar costras. La piel puede verse opaca mientras se renueva." },
  { icon: CircleCheck, title: "Semanas 3–4", text: "La superficie suele estar cicatrizada. Retoma gradualmente tus actividades y protege el tatuaje del sol." },
];

const avoidItems = [
  { icon: Sun, label: "Sol directo" }, { icon: Waves, label: "Piscina o jacuzzi" }, { icon: Hand, label: "Fricción y rascado" }, { icon: Shirt, label: "Ropa ajustada" },
];

export default function CuidadosPage() {
  const number = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "56912345678";
  return (
    <div className="bg-[var(--tattoo-bg)] px-4 py-20 text-[var(--tattoo-text)] sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl">
      <Reveal><section className="max-w-3xl" aria-labelledby="care-heading"><p className="mb-4 text-xs font-medium uppercase tracking-[.16em] text-[var(--tattoo-accent)]">Después de la sesión</p><h1 id="care-heading" className="font-[family-name:var(--font-display)] text-5xl font-bold leading-[.95] tracking-tight sm:text-7xl">Cuida tu tatuaje</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[var(--tattoo-text-muted)]">Una guía clara para acompañar tu piel durante las primeras semanas de cicatrización.</p></section></Reveal>
      <section className="mt-20" aria-labelledby="healing-heading"><Reveal><h2 id="healing-heading" className="font-[family-name:var(--font-display)] text-3xl font-bold sm:text-4xl">Etapas de cicatrización</h2></Reveal><ol className="relative mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><span className="absolute left-0 right-0 top-8 hidden h-px bg-[var(--tattoo-border)] lg:block" aria-hidden="true" />{healingStages.map(({ icon: Icon, title, text }, index) => <Reveal key={title} delay={index * .08}><li className="relative h-full border border-[var(--tattoo-border)] bg-[var(--tattoo-surface)] p-6"><div className="relative z-10 flex h-10 w-10 items-center justify-center rounded-full border border-[var(--tattoo-accent)] bg-[var(--tattoo-surface)] text-[var(--tattoo-accent)]"><Icon className="h-5 w-5" aria-hidden="true" /></div><span className="mt-7 block text-xs font-medium uppercase tracking-[.14em] text-[var(--tattoo-accent)]">0{index + 1}</span><h3 className="mt-2 font-[family-name:var(--font-display)] text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[var(--tattoo-text-muted)]">{text}</p></li></Reveal>)}</ol></section>
      <section className="mt-24" aria-labelledby="normal-heading"><Reveal><h2 id="normal-heading" className="font-[family-name:var(--font-display)] text-3xl font-bold sm:text-4xl">Conoce las señales</h2></Reveal><div className="mt-8 grid gap-4 md:grid-cols-2"><Reveal><div className="h-full border border-[var(--tattoo-border)] bg-[var(--tattoo-surface)] p-6 sm:p-8"><CircleCheck className="h-7 w-7 text-emerald-500" aria-hidden="true" /><h3 className="mt-6 font-[family-name:var(--font-display)] text-2xl font-bold">Es normal</h3><ul className="mt-4 space-y-3 text-[var(--tattoo-text-muted)]"><li>• Sensibilidad o leve enrojecimiento al inicio.</li><li>• Picazón y descamación durante la renovación.</li><li>• Que el tatuaje se vea más opaco por unos días.</li></ul></div></Reveal><Reveal delay={.1}><div className="h-full border border-[var(--tattoo-accent)]/50 bg-[var(--tattoo-accent)]/10 p-6 sm:p-8"><AlertCircle className="h-7 w-7 text-[var(--tattoo-accent)]" aria-hidden="true" /><h3 className="mt-6 font-[family-name:var(--font-display)] text-2xl font-bold">Consultá a un profesional</h3><p className="mt-4 leading-relaxed text-[var(--tattoo-text-muted)]">Ante fiebre, pus, dolor creciente o enrojecimiento que se expande, busca atención de un profesional de salud.</p></div></Reveal></div></section>
      <section className="mt-24" aria-labelledby="avoid-heading"><Reveal><p className="mb-3 text-xs font-medium uppercase tracking-[.16em] text-[var(--tattoo-accent)]">Protege el proceso</p><h2 id="avoid-heading" className="font-[family-name:var(--font-display)] text-3xl font-bold sm:text-4xl">Evitá durante 2 a 4 semanas</h2></Reveal><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{avoidItems.map(({ icon: Icon, label }, index) => <Reveal key={label} delay={index * .06}><div className="flex min-h-28 flex-col items-center justify-center gap-3 border border-[var(--tattoo-border)] bg-[var(--tattoo-surface)] p-4 text-center"><Icon className="h-6 w-6 text-[var(--tattoo-accent)]" aria-hidden="true" /><span className="text-sm text-[var(--tattoo-text-muted)]">{label}</span></div></Reveal>)}</div></section>
      <Reveal delay={.15}><section className="mt-20 border border-[var(--tattoo-accent)]/50 bg-[var(--tattoo-accent)]/10 p-6 sm:p-8" aria-label="Ayuda con la cicatrización"><h2 className="font-[family-name:var(--font-display)] text-2xl font-bold">¿Algo no se ve bien?</h2><p className="mt-3 max-w-2xl leading-relaxed text-[var(--tattoo-text-muted)]">Si tienes dudas sobre tu sesión o el proceso de cicatrización, puedes escribirme. Para síntomas de alarma, consulta siempre a un profesional de salud.</p><a className="mt-5 inline-flex items-center gap-2 font-medium text-[var(--tattoo-text)] transition-colors hover:text-[var(--tattoo-accent)]" href={`https://wa.me/${number}?text=${encodeURIComponent("Hola, tengo una pregunta sobre la cicatrización de mi tatuaje.")}`} target="_blank" rel="noopener noreferrer"><MessageCircle className="h-4 w-4" aria-hidden="true" /> Consultar por WhatsApp</a></section></Reveal>
    </div></div>
  );
}
